# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Run_Tests
  displayName: Run Tosca tests
  pool:
    name: Self-hosted Tosca
  steps:
  - checkout: self

  #Run Tosca test(s) via ToscaCIClient
  - task: PowerShell@2
    displayName: Run Tosca test(s) via ToscaCIClient
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\\run-tosca-test.ps1
      arguments: >
        -resultsFile "results\results.xml"
        -executionListFile "tests\conf-execution-list.xml"

  #Publish results to qTest
  - task: PowerShell@2
    displayName: Publish results to qTest
    condition: always()
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\tests\publish-results-to-qtest.ps1
      arguments: >
        -projectId "105466"
        -testCycle "2193247"
        -uploadResultsFile "$(System.DefaultWorkingDirectory)\results\results.xml"

  #Export PDF Report
  - task: PowerShell@2
    displayName: Export PDF Report
    #condition: always()
    #inputs:
      #targetType: 'filePath'
      #filePath: $(System.DefaultWorkingDirectory)\tests\export-pdf-report.ps1

  #Publish Test Results
  - task: PublishTestResults@2
    condition: always()
    displayName: Publish Test Results **/results/results*.xml
    inputs:
      testResultsFiles: '**/results/results*.xml'
...
