# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: self
    type: git
    ref: main

pool: 
   name: Default
   demands:
    - agent.name -equals shash-agent
    
stages:
- stage: test
  jobs:
    - job: run_tests
      displayName: Run Tosca test(s)
      steps:
#Run Tosca test(s) via AOS API
      - task: PowerShell@2
        displayName: Exeute Tosca tests
        inputs:
          targetType: 'filePath'
          filePath: $(System.DefaultWorkingDirectory)\tests\aos-api\tosca_execution_client.ps1
          arguments: >
            -toscaServerUrl "http://toscaserver23-1.toscademo.com"
            -eventsConfigFilePath "tests/eventsConfig/testEvents.json"
            -projectName "tosca_core_repo"
            -clientId "tAHtNBkvR0qcXDNsmluU1Q"
            -clientSecret "Nzj4KsZdXkSNac7HNWFduQ-6-ogoHhw0Kj7gGHVCp3Ug"
            -resultsFolderPath "$(Pipeline.Workspace)/TestResults"
            -executionEnvironment "Dex"
            -creator "ADO-ToscaExecutionClient"
            -pollingInterval "15"
            -debug "true"

# Convert results file to UFT8
      - task: PowerShell@2
        displayName: Convert results to UFT8
        inputs:
          targetType: 'inline'
          script: |
            # in case there are multiple result files, sort and take the last one (most recently created)
            $resultsFileName = (Get-ChildItem -Path "$(Pipeline.Workspace)\TestResults" -Filter '*_results.xml' | sort LastWriteTime | Select-Object -Last 1).name
            $resFilePath = "$(Pipeline.Workspace)\TestResults\$resultsFileName"
            $content = Get-Content -Path $resFilePath -Raw
            Set-Content -Encoding UTF8 -Path $resFilePath $content

#Publish Test Results
      - task: PublishTestResults@2
        displayName: Publish results
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(Pipeline.Workspace)\TestResults\*_results.xml'
